# This block automatically generated by p10k
###############################################################################
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
###############################################################################

alias ga="git add"
alias gb="git branch"
alias gba="git branch --all"
alias gbd="git branch --delete"
alias gcam="git commit --all --message"
alias gcl="git clone --recurse-submodules"
alias gco="git checkout"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git pull"
alias glg="git log --stat"
alias glog="git log --oneline --decorate --graph"
alias gp="git push"
alias gra="git remote add"
alias grv="git remote --verbose"
alias gss="git status --short"
alias gst="git status"
