{ pkgs, ...}:
{
  environment.systemPackages = with pkgs; [
        anki
        bat
        bottles
        brave
        btop
        deluge
        fd
        ferdium
        file
        gcc
        git
        gnupg
        kdePackages.yakuake
        lsd
        lutris
        meslo-lgs-nf
        mpv
        nodejs-slim
        obsidian
        pass
        pinentry-qt
        polonium
        prismlauncher
        python3
        renameutils
        ripgrep
        stow
        thunderbird
        tmux
        tree-sitter
        unrar-free
        unzip
        vesktop
        wl-clipboard
        zathura
        zotero_7
        zsh-powerlevel10k
  ];
}
