#[Sunsetr configuration]
backend = "auto"                 # Backend to use: "auto", "hyprland" or "wayland"
start_hyprsunset = true          # Set true if you're not using hyprsunset.service
startup_transition = true        # Enable smooth transition when sunsetr starts
startup_transition_duration = 60 # Duration of startup transition in seconds (1-60)
night_temp = 4900                # Color temperature after sunset (1000-20000) Kelvin
day_temp = 6500                  # Color temperature during day (1000-20000) Kelvin
night_gamma = 95                 # Gamma percentage for night (10-100%)
day_gamma = 100                  # Gamma percentage for day (10-100%)
update_interval = 300            # Update frequency during transitions in seconds (10-300)
transition_mode = "geo"          # Select: "geo", "finish_by", "start_at", "center"

#[Manual transitions]
sunset  = "00:00:00"  # ignored in geo mode
sunrise = "12:00:00"  # ignored in geo mode
